#!/usr/bin/env python
import pika

conn_param= pika.ConnectionParameters(
    host = 'localhost',
    credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)

channel = connection.channel()

channel.queue_declare(queue='hello')


def callback(ch, method, properties, body):
        print(" [x] Received %r" % body)


channel.basic_consume(callback,queue='hello',no_ack=True)

print(' [*] Waiting for messages. To exit press CTRL+C')
channel.start_consuming()

connection.close()
