#!/usr/bin/env python
import pika
import sys

conn_param= pika.ConnectionParameters(
    host = 'localhost',
    credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)

channel = connection.channel()

channel.exchange_declare(exchange='sms',
                         type='direct')

result = channel.queue_declare(exclusive=True)
queue_name = result.method.queue

numbers = sys.argv[1:]
if not numbers:
    sys.stderr.write("Usage: %s [number] [number]\n" % sys.argv[0])
    sys.exit(1)

for number in numbers:
    channel.queue_bind(exchange='sms',
                       queue=queue_name,
                       routing_key=number)

print(' [*] Waiting for logs. To exit press CTRL+C')

def callback(ch, method, properties, body):
    print(" [x] %r:%r" % (method.routing_key, body))

channel.basic_consume(callback,
                      queue=queue_name,
                      no_ack=True)

channel.start_consuming()
