#!/usr/bin/env python
import pika
import sys

conn_param= pika.ConnectionParameters(
            host = 'localhost',
            credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)


channel = connection.channel()


channel.exchange_declare(exchange='fax', type='headers')

company = sys.argv[1] if len(sys.argv) > 1 else 'abccompany'
processor = sys.argv[2] if len(sys.argv) > 2 else 'standard'
message = sys.argv[3] if len(sys.argv) > 3 else 'default message' 

headers = { 'customer' : company , 'processor' : processor}


channel.basic_publish(exchange='fax', routing_key='', body=message,
        properties = pika.BasicProperties(headers = headers, delivery_mode = 2))


print(" [x] Sent to %r:%r" % (company, message))
connection.close()
