#!/usr/bin/env python
import sys
import time

import pika

sleep = sys.argv[1] if len(sys.argv)>1 else "1"

sleep = int(sleep)

conn_param= pika.ConnectionParameters(
    host = 'localhost',
    credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)

channel = connection.channel()

channel.queue_declare(queue='durable_queue',durable=True)


def callback(ch, method, properties, body):
    print(" [x] Received %r" % body)
    time.sleep(sleep)
    print( "Execution completed for " + body)
    ch.basic_ack(method.delivery_tag)


channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback,queue='durable_queue')

print(' [*] Waiting for messages. To exit press CTRL+C')
channel.start_consuming()

connection.close()
