#!/usr/bin/env python
import pika
import sys

body = sys.argv[1] if len(sys.argv)>1 else "no argument"

conn_param= pika.ConnectionParameters(
    host = 'localhost',
    credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)

channel = connection.channel()

channel.queue_declare(queue='durable_queue', durable=True)

channel.basic_publish(exchange='',
                      routing_key='durable_queue',
                      body=body,
                      properties=pika.BasicProperties(delivery_mode = 2))
print(" [x] Sent '" + body + "'")
connection.close()
