#!/usr/bin/env python
import pika
import sys

conn_param= pika.ConnectionParameters(
            host = 'localhost',
                credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)


channel = connection.channel()


channel.exchange_declare(exchange='sms_topic',
                                 type='topic')

number = sys.argv[1] if len(sys.argv) > 2 else 'info'
message = sys.argv[2]
channel.basic_publish(exchange='sms_topic', routing_key=number, body=message)


print(" [x] Sent %r:%r" % (number, message))
connection.close()
