#!/usr/bin/env python
import pika

conn_param= pika.ConnectionParameters(
    host = 'localhost',
    credentials = pika.credentials.PlainCredentials('admin','admin'))

connection = pika.BlockingConnection(conn_param)

channel = connection.channel()

channel.queue_declare(queue='durable_queue',durable=True)


def callback(ch, method, properties, body):
    print(" [x] Received %r" % body)
    try:
        intvalue=int(body)
        if (intvalue % 2 != 0):
            raise
        print( "Execution completed for " + body)
        ch.basic_ack(method.delivery_tag)
    except:
        print("Bug found")


channel.basic_consume(callback,queue='durable_queue')

print(' [*] Waiting for messages. To exit press CTRL+C')
channel.start_consuming()

connection.close()
